# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ea9abb85fca856681f37d650d80906545ca4fba67fa5dc6f4cb0ceece8d12b67e6194831a8a77502850f88f9f7ce8b04f7c6a533f0fe7181dd0f2cadef6608

test:
  secret_key_base: 4b5bbcf674ff2b0a095f4eebf907ea13c50a0cc908553535d9d4662b126ebeff6785bf022441985bbd0bbc5479e193ad43ad421869ce553b48c07381c82d5918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
